### ISSUE TITLE
Protect master and gh-pages branch from pushes

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/organization#3]
Leaving direct push to @new-xkit/owners and the update bot

**Comment by hobinjk** [comment]
Done, master is protected with status checks, gh-pages is protected.
Protected: "Disables force-pushes to this branch and prevents it from being deleted."
Require status checks to pass before merging: "commits must first be pushed to another branch, then merged or pushed directly to master after status checks have passed."
Hopefully this doesn't break anything.

**Comment by nightpool** [comment]
It looks like homu is a "required status check" now? so we can only use homu to merge to master?

Not sure if this was the intended effect

**Comment by hobinjk** [comment]
Yes, that's intended. I don't think there's any situation (other than a Homu outage) in which we would want to ignore the homu check but not the travis-ci check.

**Comment by nightpool** [comment]
homu outage, but also any outside-of-PR merges, no?

**Comment by dlmarquis** [comment]
Yes, we had decided to bar everyone from merging directly to master, except @hobinjk and I in the case it's absolutely necessary. This was to prevent abuse, or the more likely case of accidentally hitting "merge directly to master" instead of "create new branch"

**Comment by nightpool** [comment]
@dlmarquis but abuse and "push directly to master" in the web interface was
canceled out by just making them _regular_ protected branches

**Comment by hobinjk** [comment]
@nightpool What sort of non-PR merges did you have in mind?

I believe that the benefits in code quality from having multiple eyes look over changes outweigh the delay for review. This is a sample size of one, but your PR https://github.com/new-xkit/XKit/pull/865 is a very well-handled case of an emergency Staff breakage PR that went out quickly with quality.

**Comment by nightpool** [comment]
@hobinjk mainly times when PR authors can't/don't know how to merge, but I
guess we can handle that with even more PRs

Down to keep this like this until we feel we might need to change it though
